# configuration file for MediaWikiCrawler. For each MediaWiki to crawl, at least wikiName and wikiURL are required.
# Each Wiki description has to start with a minus "-" 
# 
# sample
#         # Unique name of this wiki, like "Wikipedia (en)". Required parameter.
#    - wikiName: "Wikipedia (en)"
#         # Path to the Wiki, like "http://en.wikipedia.org/". Required parameter.
#      wikiURL: "http://en.wikipedia.org/"
#         # Path to api.php, relative from wikiURL, like "/w/" for wikipedia. Must not contain the file name api.php
#         # Do not forget the "/" in  the end of the path if there is any.
#         # Optional parameter. Leave empty if unknown. 		
#      pathToAPI: "/w/" 
#         # Path to wiki pages, relative from wiki_url, like /wiki/ as used in wikipedia (resulting path is http://de.wikipedia.org/wiki/)         
#         # Do not forget the "/" in  the end of the path if there is any. 
#         # Optional parameter. Leave empty if unknown.
#      pathToContent: "/wiki/"
#         # User name to use for crawling.
#         # Optional parameter. 
#      crawlerUserName: "myname" 
#         # The user's password. Optional parameter. 
#      crawlerPassword: "mysecret"
#         # The namespaceIDs to include into crawling, separated by comma ",". All pages within these namespaces are crawled.
#         # namespaceIDs that do not exist in the Wiki are ignored.
#         # known bug: to crawl a single namespace, add comma like "1,", otherwise all namespaces are crawled! 
#         # Optional parameter. Leave empty to crawl all namespaces.
#      namespacesToCrawl: "0, 1, 12" 
#
# plain sample 
#    - wikiName: 
#      wikiURL:  		
#      pathToAPI:
#      pathToContent:
#      crawlerUserName:
#      crawlerPassword: 
#      namespacesToCrawl:


wikiConfigurations:
#    - wikiName: "Aletheia Projektwiki"
#      wikiURL: "http://87.106.216.160/aletheia/"
#      pathToContent: "/index.php/"
#      crawlerUserName: "Sandro Crawler"
#      crawlerPassword: "crawler"
#      namespacesToCrawl: "0, 1, 3"
#    - wikiName: "Wikipedia (bjn)"
#      wikiURL: "http://bjn.wikipedia.org/"
#      pathToAPI: "/w/"
#      pathToContent: "/wiki/"
#      namespacesToCrawl: "0, "
#    - wikiName: "Wikipedia (yo)"
#      wikiURL: "http://yo.wikipedia.org/"
#      pathToAPI: "/w/"
#      pathToContent: "/wiki/"
#      namespacesToCrawl: "0, "
#    - wikiName: "Wikipedia (simple)"
#      wikiURL: "http://simple.wikipedia.org/"
#      pathToAPI: "/w/"
#      pathToContent: "/wiki/"
#      namespacesToCrawl: "0, "
    - wikiName: "Wikipedia (en)"
      wikiURL: "http://en.wikipedia.org/"
      pathToAPI: "/w/"
      pathToContent: "/wiki/"
#      namespacesToCrawl: "0, "